[package]
name = "rtlib"
version = "0.0.1"
authors = ["Rene Zeto <rwzeto@gmail.com>"]
edition = "2018"

[lib]
name = "rtlib"
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0.21.1"

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]